import "./globals.css"

import type { Metadata } from "next";
import { Inter } from "next/font/google";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const fontSans = Inter({
    subsets: ["latin"],
    variable: "--font-sans",
})

export default function RootLayout({
    children,
    params: { locale }
}: Readonly<{
    children: React.ReactNode;
    params: { locale: string };
}>) {
    return children;
}
